name: Test
<<<<<<< HEAD
on: [push, pull_request]
=======
on: [push, pull]
>>>>>>> 76bf98095f12de2b592e46f3ded3a2383cb1e884

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.7.x, 2.6.x, 2.5.x, jruby]
        BUNDLE_GEMFILE:
          - gemfiles/ar50.gemfile
          - gemfiles/ar51.gemfile
          - gemfiles/ar52.gemfile
          - gemfiles/ar60.gemfile
          - gemfiles/ar61.gemfile
          - gemfiles/rgeo1.gemfile
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake
